### ISSUE TITLE
readme.md has two headings <iron-meta> and <iron-meta-query> with identical contents

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/iron-meta#35]
readme.md has two headings <iron-meta> and <iron-meta-query> with identical contents. I believe the second half should go...

**Comment by dman777** [comment]
I was wondering about this also.

**Comment by MitulGedeeya** [comment]
i just came here to report this bug ! :)

**Comment by sujay1848** [comment]
Shouldn't the second block with the header `iron-meta-query` hold content about how to use `iron-meta-query`?

**Comment by rictic** [comment]
Fixed by https://github.com/PolymerElements/iron-meta/commit/81f604e0ab670db49bd4dca130b50ebd5c58c166
