### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by brettpostin** [PolymerElements/iron-meta#47]
### Description
A syntax error is thrown in IE11 when not transpiled or served through "polymer serve".

`SCRIPT1003: Expected ':'`

I'm assuming due to es6 syntax? The offending line is:

      byKey(key) {
        this.key = key;
        return this.value;
      }

My understanding is that these elements should be in hybrid mode to work in 1.x and 2.x. So transpilation should not be a prerequisite. Please correct me if that assumption is wrong!

Changing to the following solves the problem:

      byKey: function(key) {
        this.key = key;
        return this.value;
      }

### Steps to reproduce

1. Put a `iron-meta` element in the page.
2. Open the page in a web browser.
3. Check IE11 dev tools.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ X ] IE 11

**Comment by krumware** [comment]
+1, this is bugging us out as well

**Comment by keanulee** [comment]
Fixed by #49
