### ISSUE TITLE
Documentation confusing

### ISSUE THREAD

**Issue by zacharytamas** [PolymerElements/iron-meta#7]
The documentation (README or the comment doc in the HTML file) doesn't mention `iron-meta-query` which is bundled with `iron-meta`. 

The documentation for both show how they can be used to get data out of `iron-meta`, which leads me to wonder by the `iron-meta-query` exists at all. Noteably, the `iron-meta` documentation says:

```
Now I can access that element (and it's metadata) from any iron-meta instance 
via the byKey method [...]
```

If `iron-meta` can be used to get the data from others too, it raises a question of the utility of the `iron-meta-query`.

Could the documentation be updated to more comprehensively describe how these work together?

Thanks!

**Comment by notwaldorf** [comment]
@sjmiles Could you add a little blurb to the documentation for this case? Thanks!

**Comment by m4b** [comment]
+1 documentation does not seem to be correct on accessing a key's value.

Specifically we're told that:

> Now I can access that element (and it's metadata) from any iron-meta instance via the byKey method, e.g.
>
> `meta.byKey('info').getAttribute('value');`

but to access the value, you need to actually just do: `meta.byKey('info');`

**Comment by Mipme** [comment]
+1 for better documentation.

I would very much value adding explanations on how to properly set values on the iron-meta programmatically. From the code there are two possibilities: `_register` and `_registerKeyValue`. But these two methods are with a twist! You got to know which list/_metaDatas you want your value to be stored to.

**Comment by danhawkes** [comment]
@Mipme Agreed.

It's also not clear to me what the inden

**Comment by danhawkes** [comment]
It's also not clear to me from the docs how to define multiple key/value pairs:

> `<iron-meta key="info" value="foo/bar"></iron-meta>`
 
> Note that value="foo/bar" is the metadata I've defined.I could define more attributes or use child nodes to define additional metadata.

"More attributes" doesn't make sense, so does it mean the same attributes, on multiple instances? e.g.

    <iron-meta key="one" value="foo/bar"></iron-meta>
    <iron-meta key="two" value="baz"></iron-meta>

**Comment by bendavis78** [comment]
Why does there need to be `iron-meta` and `iron-meta-query`? Why not just have one element that gets/sets the singleton value?
